// Builds the static, peer-to-peer version of the game into dist/ — no server
// needed, so it can be hosted anywhere (the repo publishes it to GitHub Pages).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'dist');

const copy = (from, to) => {
  const dest = path.join(OUT, to);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.cpSync(path.join(ROOT, from), dest, { recursive: true });
};

fs.rmSync(OUT, { recursive: true, force: true });
copy('public', '.');

// Only the vendor files the game actually loads.
copy('node_modules/three/build/three.module.js', 'vendor/three/three.module.js');
copy('node_modules/three/build/three.core.js', 'vendor/three/three.core.js');
copy('node_modules/three/examples/jsm/environments/RoomEnvironment.js', 'vendor/three/addons/environments/RoomEnvironment.js');
copy('node_modules/peerjs/dist/peerjs.min.js', 'vendor/peerjs/peerjs.min.js');
copy('node_modules/uqr/dist/index.mjs', 'vendor/uqr/index.mjs');

// Screen and phone talk peer-to-peer instead of through the Node server.
fs.writeFileSync(
  path.join(OUT, 'js/config.js'),
  "// Generated by scripts/build-static.js for static hosting.\nexport const MODE = 'p2p';\n",
);

// Short, typeable phone address: <site>/c
copy('public/controller.html', 'c.html');
fs.writeFileSync(path.join(OUT, '.nojekyll'), '');

console.log(`Static site ready in ${path.relative(ROOT, OUT)}/`);
